const emojis = [
  { name: "gorilla", emoji: "🦍" },
  { name: "dog face", emoji: "🐶" },
  { name: "dog", emoji: "🐕" },
  { name: "poodle", emoji: "🐩" },
  { name: "wolf", emoji: "🐺" },
  { name: "fox", emoji: "🦊" },
  { name: "cat face", emoji: "🐱" },
  { name: "cat", emoji: "🐈" },
  { name: "lion", emoji: "🦁" },
  { name: "tiger face", emoji: "🐯" },
  { name: "tiger", emoji: "🐅" },
  { name: "leopard", emoji: "🐆" },
  { name: "horse face", emoji: "🐴" },
  { name: "horse", emoji: "🐎" },
  { name: "unicorn", emoji: "🦄" },
  { name: "zebra", emoji: "🦓" },
  { name: "deer", emoji: "🦌" },
  { name: "cow face", emoji: "🐮" },
  { name: "ox", emoji: "🐂" },
  { name: "water buffalo", emoji: "🐃" },
  { name: "cow", emoji: "🐄" },
  { name: "boar", emoji: "🐗" },
  { name: "ram", emoji: "🐏" },
  { name: "ewe", emoji: "🐑" },
  { name: "goat", emoji: "🐐" },
  { name: "camel", emoji: "🐫" },
  { name: "llama", emoji: "🦙" },
  { name: "giraffe", emoji: "🦒" },
  { name: "elephant", emoji: "🐘" },
  { name: "rhinoceros", emoji: "🦏" },
  { name: "hippopotamus", emoji: "🦛" },
  { name: "mouse face", emoji: "🐭" },
  { name: "mouse", emoji: "🐁" },
  { name: "rat", emoji: "🐀" },
  { name: "hamster", emoji: "🐹" },
  { name: "rabbit face", emoji: "🐰" },
  { name: "rabbit", emoji: "🐇" },
  { name: "chipmunk", emoji: "🐿️" },
  { name: "hedgehog", emoji: "🦔" },
  { name: "bat", emoji: "🦇" },
  { name: "penguin", emoji: "🐧" },
  { name: "frog", emoji: "🐸" },
  { name: "crocodile", emoji: "🐊" },
  { name: "duck", emoji: "🦆" },
  { name: "swan", emoji: "🦢" },
  { name: "owl", emoji: "🦉" },
  { name: "eagle", emoji: "🦅" },
  { name: "duckling", emoji: "🐤" },
  { name: "dove", emoji: "🕊️" },
  { name: "turkey", emoji: "🦃" },
  { name: "rooster", emoji: "🐓" },
  { name: "chicken", emoji: "🐔" },
  { name: "peacock", emoji: "🦚" },
  { name: "parrot", emoji: "🦜" },
  { name: "spider", emoji: "🕷️" },
  { name: "scorpion", emoji: "🦂" },
  { name: "mosquito", emoji: "🦟" },
  { name: "worm", emoji: "🐛" },
  { name: "cricket", emoji: "🦗" },
  { name: "ant", emoji: "🐜" },
  { name: "bee", emoji: "🐝" },
  { name: "beetle", emoji: "🪲" },
  { name: "butterfly", emoji: "🦋" },
  { name: "snail", emoji: "🐌" },
  { name: "snake", emoji: "🐍" },
  { name: "lizard", emoji: "🦎" },
  { name: "sauropod", emoji: "🦕" },
  { name: "t-rex", emoji: "🦖" },
  { name: "crab", emoji: "🦀" },
  { name: "lobster", emoji: "🦞" },
  { name: "shrimp", emoji: "🦐" },
  { name: "squid", emoji: "🦑" },
  { name: "octopus", emoji: "🐙" },
  { name: "shark", emoji: "🦈" },
  { name: "whale", emoji: "🐳" },
  { name: "dolphin", emoji: "🐬" },
  { name: "fish", emoji: "🐟" },
  { name: "blowfish", emoji: "🐡" },
  { name: "tropical fish", emoji: "🐠" },
  { name: "seahorse", emoji: "🐬" },
  { name: "crab", emoji: "🦀" },
  { name: "lobster", emoji: "🦞" },
  { name: "shrimp", emoji: "🦐" },
  { name: "squid", emoji: "🦑" },
  { name: "octopus", emoji: "🐙" },
  { name: "bison", emoji: "🦬" },
  { name: "beaver", emoji: "🦫" },
  { name: "seal", emoji: "🦭" },
  { name: "grapes", emoji: "🍇" },
  { name: "melon", emoji: "🍈" },
  { name: "watermelon", emoji: "🍉" },
  { name: "tangerine", emoji: "🍊" },
  { name: "lemon", emoji: "🍋" },
  { name: "banana", emoji: "🍌" },
  { name: "pineapple", emoji: "🍍" },
  { name: "mango", emoji: "🥭" },
  { name: "red apple", emoji: "🍎" },
  { name: "green apple", emoji: "🍏" },
  { name: "pear", emoji: "🍐" },
  { name: "peach", emoji: "🍑" },
  { name: "cherries", emoji: "🍒" },
  { name: "strawberry", emoji: "🍓" },
  { name: "kiwi", emoji: "🥝" },
  { name: "tomato", emoji: "🍅" },
  { name: "coconut", emoji: "🥥" },
  { name: "avocado", emoji: "🥑" },
  { name: "eggplant", emoji: "🍆" },
  { name: "potato", emoji: "🥔" },
  { name: "carrot", emoji: "🥕" },
  { name: "corn", emoji: "🌽" },
  { name: "hot pepper", emoji: "🌶️" },
  { name: "bell pepper", emoji: "🫑" },
  { name: "cucumber", emoji: "🥒" },
  { name: "leafy green", emoji: "🥬" },
  { name: "broccoli", emoji: "🥦" },
  { name: "garlic", emoji: "🧄" },
  { name: "onion", emoji: "🧅" },
  { name: "mushroom", emoji: "🍄" },
  { name: "peanuts", emoji: "🥜" },
  { name: "chestnut", emoji: "🌰" },
  { name: "bread", emoji: "🍞" },
  { name: "croissant", emoji: "🥐" },
  { name: "baguette bread", emoji: "🥖" },
  { name: "pretzel", emoji: "🥨" },
  { name: "cheese wedge", emoji: "🧀" },
  { name: "burger", emoji: "🍔" },
  { name: "french fries", emoji: "🍟" },
  { name: "pizza", emoji: "🍕" },
  { name: "hot dog", emoji: "🌭" },
  { name: "sandwich", emoji: "🥪" },
  { name: "taco", emoji: "🌮" },
  { name: "burrito", emoji: "🌯" },
  { name: "stuffed flatbread", emoji: "🥙" },
  { name: "falafel", emoji: "🧆" },
  { name: "thumbs up", emoji: "👍" },
  { name: "fire", emoji: "🔥" },
  { name: "heart", emoji: "❤️" },
  { name: "star", emoji: "⭐" },
  { name: "rainbow", emoji: "🌈" },
  { name: "house", emoji: "🏠" },
  { name: "car", emoji: "🚗" },
  { name: "computer", emoji: "💻" },
  { name: "rocket", emoji: "🚀" },
  { name: "money bag", emoji: "💰" },
  { name: "key", emoji: "🔑" },
  { name: "wrench", emoji: "🔧" },
  { name: "screwdriver", emoji: "🪛" },
  { name: "hammer", emoji: "🔨" },
  { name: "watch", emoji: "⌚" },
  { name: "telephone", emoji: "☎️" },
  { name: "camera", emoji: "📷" },
  { name: "television", emoji: "📺" },
  { name: "sun with face", emoji: "🌞" },
  { name: "moon", emoji: "🌕" },
  { name: "crescent moon", emoji: "🌙" },
  { name: "star and crescent", emoji: "☪️" },
  { name: "wheel of dharma", emoji: "☸️" },
  { name: "peace symbol", emoji: "☮️" },
  { name: "atom symbol", emoji: "⚛️" },
  { name: "skull", emoji: "💀" },
  { name: "pill", emoji: "💊" },
  { name: "syringe", emoji: "💉" },
  { name: "microbe", emoji: "🦠" },
  { name: "shower", emoji: "🚿" },
  { name: "coffin", emoji: "⚰️" },
];

const adjectives = [
  "able",
  "abiding",
  "absorbed",
  "absorbing",
  "acceptable",
  "accessible",
  "accidental",
  "accurate",
  "acid",
  "acoustic",
  "actually",
  "adamant",
  "adaptable",
  "addicted",
  "adhesive",
  "adorable",
  "adventurous",
  "ahead",
  "alert",
  "alive",
  "alluring",
  "amazing",
  "ambitious",
  "amused",
  "amusing",
  "ancient",
  "animated",
  "apathetic",
  "aquatic",
  "aromatic",
  "aspiring",
  "astonishing",
  "attractive",
  "auspicious",
  "automatic",
  "available",
  "awesome",
  "axiomatic",
  "beautiful",
  "befitting",
  "beneficial",
  "bent",
  "best",
  "better",
  "big",
  "billowy",
  "bite-sized",
  "bitter",
  "bizarre",
  "black-and-white",
  "bloody",
  "blue-eyed",
  "blushing",
  "brainy",
  "brave",
  "brawny",
  "breakable",
  "breezy",
  "bright",
  "bright",
  "broad",
  "brown",
  "bumpy",
  "burly",
  "busy",
  "calculating",
  "callous",
  "calm",
  "capable",
  "capricious",
  "careful",
  "careless",
  "caring",
  "cautious",
  "ceaseless",
  "certain",
  "charming",
  "cheap",
  "cheerful",
  "chemical",
  "chief",
  "childlike",
  "chilly",
  "chivalrous",
  "chubby",
  "chunky",
  "classy",
  "clean",
  "clear",
  "clever",
  "coherent",
  "colorful",
  "colossal",
  "comfortable",
  "common",
  "complete",
  "complex",
  "concerned",
  "confused",
  "conscious",
  "cool",
  "cooperative",
  "coordinated",
  "courageous",
  "cultured",
  "curious",
  "cute",
  "daily",
  "damp",
  "dapper",
  "dark",
  "dashing",
  "dazzling",
  "deafening",
  "dear",
  "debonair",
  "decisive",
  "decorous",
  "deep",
  "deeply",
  "defeated",
  "defective",
  "defiant",
  "delicate",
  "delicious",
  "delightful",
  "demonic",
  "delirious",
  "dependent",
  "descriptive",
  "detailed",
  "determined",
  "devilish",
  "didactic",
  "different",
  "diligent",
  "direful",
  "discreet",
  "disgusted",
  "disgusting",
  "disillusioned",
  "distinct",
  "disturbed",
  "divergent",
  "dizzy",
  "domineering",
  "drab",
  "dramatic",
  "dreary",
  "dry",
  "dull",
  "dynamic",
  "eager",
  "early",
  "earthy",
  "easy",
  "economical",
  "educated",
  "efficacious",
  "efficient",
  "elastic",
  "elated",
  "electric",
  "elegant",
  "elfin",
  "elite",
  "embarrassed",
  "eminent",
  "empty",
  "enchanted",
  "enchanting",
  "encouraging",
  "endurable",
  "energetic",
  "enormous",
  "entertaining",
  "enthusiastic",
  "envious",
  "equable",
  "equal",
  "erect",
  "ethereal",
  "evanescent",
  "evasive",
  "excellent",
  "excited",
  "exciting",
  "exclusive",
  "exotic",
  "expensive",
  "exuberant",
  "exultant",
  "fabulous",
  "faded",
  "fair",
  "faithful",
  "famous",
  "fanatical",
  "fancy",
  "fantastic",
  "far-flung",
  "fascinated",
  "fast",
  "fat",
  "fearless",
  "feeble",
  "female",
  "fertile",
  "festive",
  "few",
  "fierce",
  "filthy",
  "fine",
  "finicky",
  "first",
  "fixed",
  "flagrant",
  "flaky",
  "flashy",
  "flat",
  "flawless",
  "flimsy",
  "fluffy",
  "fluttering",
  "foamy",
  "foolish",
  "fortunate",
  "frail",
  "fragile",
  "frantic",
  "free",
  "fresh",
  "friendly",
  "frightened",
  "frightening",
  "full",
  "functional",
  "funny",
  "furry",
  "furtive",
  "futuristic",
  "fuzzy",
  "gabby",
  "gainful",
  "gamy",
  "gaping",
  "garrulous",
  "gaudy",
  "general",
  "gentle",
  "giant",
  "galactic",
  "gallant",
  "galore",
  "game-changing",
  "gamesome",
  "gemmy",
  "generous",
  "gentle",
  "genuine",
  "giddy",
  "gifted",
  "glad",
  "gladsome",
  "glamorous",
  "gleaming",
  "gleeful",
  "glistening",
  "glittering",
  "glorious",
  "glossy",
  "glowing",
  "good",
  "goodhearted",
  "goodly",
  "gorgeous",
  "graceful",
  "gracious",
  "grand",
  "grateful",
  "gratified",
  "gratifying",
  "great",
  "greater",
  "greatest",
  "giddy",
  "groundbreaking",
  "groovy",
  "guided",
  "guiltless",
  "gumption",
  "jovial",
  "joyful",
  "joyous",
  "jubilant",
  "keen",
  "kind",
  "kind-hearted",
  "knowledgeable",
  "kooky",
  "laid-back",
  "laudable",
  "lavish",
  "leading",
  "learned",
  "legendary",
  "lenient",
  "liberal",
  "light-hearted",
  "likable",
  "lively",
  "lofty",
  "logical",
  "long-lasting",
  "lovable",
  "lovely",
  "loving",
  "loyal",

  "safe",
  "satisfied",
  "secure",
  "selective",
  "serene",
  "sharp",
  "shiny",
  "significant",
  "silent",
  "simple",
  "sincere",
  "skillful",
  "smart",
  "smiling",
  "smooth",
  "snug",
  "soaring",
  "sociable",
  "soft",
  "solid",
  "sophisticated",
  "sparkling",
  "special",
  "spirited",
  "splendid",
  "spotless",
  "stable",
  "stainless",
  "steady",
  "stimulating",
  "stunning",
  "stupendous",
  "stylish",
  "sublime",
  "successful",
  "sufficient",
  "sunny",
  "super",
  "superb",
  "supportive",
  "surprising",
  "sustainable",
  "sweet",
  "swell",
  "swift",
  "sympathetic",
  "tactful",
  "talented",
  "teachable",
  "tempting",
  "tenacious",
  "terrific",
  "thankful",
  "thoughtful",
  "thrilling",
  "thriving",
  "tidy",
  "timely",
  "tireless",
  "tolerant",
  "top",
  "tough",
  "tranquil",
  "treasured",
  "tremendous",
  "triumphant",
  "trusting",
  "truthful",
  "ultimate",
  "unbeatable",
  "unbiased",
  "uncommon",
  "understanding",
  "undisputed",
  "unforgettable",
  "unique",
  "united",
  "upbeat",
  "upright",
  "upward",
  "usable",
  "useful",
  "valiant",
  "valid",
  "valuable",
  "vast",
  "venerable",
  "vibrant",
  "victorious",
  "vigilant",
  "virtuous",
  "vital",
  "vivacious",
  "wealthy",
  "welcome",
  "well",
  "whole",
  "wholesome",
  "willing",
  "wonderful",
  "wondrous",
  "worthy",
  "youthful",
  "zealous",
];
module.exports = { emojis, adjectives };
