import Head from "next/head";
import styles from "../styles/Home.module.scss";
import tabel from "../styles/Tabel.module.scss";
import Header from "../components/Header";
import { LIST_CARD, GET_STATS, TRENDING_CARD } from "../graphQL/queries";
import { INACTIVATE_CARD } from "../graphQL/mutations";
import { useMutation, useQuery } from "@apollo/client";

import { useEffect, useState, useContext } from "react";
import Typography from "../components/Typography";
import Card from "../components/Card";
import Alignment from "../components/Alignment";
import Spacer from "../components/Spacer";
import Table from "../components/Tabel";
import Button from "../components/Button";
import Edit from "../components/Edit";
import Alert from "../components/Alert";
import { toaster } from "evergreen-ui";

const titles = [
  {
    name: "Questions",
    size: "25%",
  },
  {
    name: "Group",
    size: "20%",
  },
  {
    name: "Submitted by",
    size: "15%",
  },
  {
    name: "Status",
    size: "15%",
  },

  {
    name: "Pro/Normal",
    size: "15%",
  },
  {
    name: "Response",
    size: "10%",
  },
];

export default function Cards() {
  const [listCards, setlistCards] = useState([]);
  const [showModal, setshowModal] = useState(false);
  const [openCard, setopenCard] = useState(null);
  const [showAlert, setshowAlert] = useState(false);
  const [page, setpage] = useState(0);

  const [filter, setfilter] = useState(null);

  const [stats, setstats] = useState({});
  const [trending, settrending] = useState([]);
  const [filterSelected, setfilterSelected] = useState("");
  const [query, setquery] = useState("");

  const getstats = useQuery(GET_STATS, {
    onCompleted(data) {
      setstats(data?.AdminStats?.json);
    },
  });
  const getTrending = useQuery(TRENDING_CARD, {
    onCompleted(data) {
      settrending(data?.AdminListTrendingCards);
    },
  });

  const getListCards = useQuery(LIST_CARD, {
    variables: {
      limit: 10,
      page: page,
      status: filter,
    },
    onCompleted(data) {
      setlistCards(data?.AdminListCards);
      console.log(data);
    },
    onError(error) {
      console.log(error);
    },
  });

  const [makeInactive, makeInactiveQuery] = useMutation(INACTIVATE_CARD, {
    onCompleted(data) {
      console.log(data);
      toaster.success("Card inactivated");
      getListCards.refetch();
    },

    onError(error) {
      console.log(error);
      toaster.danger(error.message);
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Cards" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <Spacer height={30} />

        <Alignment direction="row">
          <Card
            text={`Total number\nof Questions`}
            number={stats?.total_questions}
            emoji="❓"
          />
          <Spacer width={27} />
          <Card
            text={`Questions created\nby Admin`}
            number={stats?.total_question_by_admin}
            emoji="👨‍💼"
          />

          <Spacer width={27} />
          <Card
            text={`Questions created\nby Users`}
            number={stats?.total_question_by_users}
            emoji="😎"
          />
          <Spacer width={27} />
          <Card
            text={`Trending Card`}
            // number={`${String(trending[0]?.caption_text).substring(0, 30)}`}
            emoji="🃏"
            // textType="h2"
            children={
              <Alignment justify="space-between" direction="row">
                <Typography
                  text={`${String(trending[0]?.caption_text).substring(0, 30)}`}
                  type={"h2"}
                  color="black"
                  style={{
                    width: "50%",
                  }}
                />
                <Alignment align="flex-start" direction="column">
                  <Typography text="Messages" type={"h7"} color="black" />
                  <Typography
                    text={trending[0]?.total_messages_count}
                    type={"h2"}
                    color="black"
                  />
                </Alignment>
              </Alignment>
            }
          />
        </Alignment>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="All Cards" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          columns={5}
          titles={titles}
          btnText="Edit"
          onPress={() => {}}
          onNext={() => {
            if (Math.ceil(stats?.total_questions / 10) !== page + 1) {
              setpage(page + 1);
            }
          }}
          onPrev={() => {
            if (page >= 1) {
              setpage(page - 1);
            }
          }}
          totalNumber={Math.ceil(stats?.total_questions / 10)}
          currentNumber={page + 1}
          filterSelected={filterSelected}
          filterList={[
            "All",
            "Normal",
            "Pro",
            "Admin",
            "User",
            "Live",
            "Priotized",
            "Private",
            "Inactive",
            "Live_awaiting",
          ]}
          onSelectFilter={(item) => {
            setfilterSelected(item);
            if (
              [
                "live",
                "inactive",
                "private",
                "priotized",
                "live_awaiting",
              ].includes(item?.toLowerCase())
            ) {
              setfilter(item?.toLowerCase());
            } else {
              setfilter(null);
            }
          }}
          onSearch={(val) => {
            setquery(val);
          }}
        >
          {listCards
            .filter((item) => {
              if (filterSelected == "All" && query == "") {
                return true;
              } else {
                return (
                  item.status
                    .toLowerCase()
                    .indexOf(filterSelected.toLowerCase()) !== -1 ||
                  (item.is_premium && filterSelected.toLowerCase() == "pro") ||
                  (!item.is_premium &&
                    filterSelected.toLowerCase() == "normal") ||
                  filterSelected.toLowerCase() == "admin" ||
                  filterSelected.toLowerCase() == "user" ||
                  item?.caption_text
                    ?.toLowerCase()
                    ?.includes(query.toLowerCase())
                );
              }
            })
            .map((item, index) => {
              return (
                <CardItem
                  onDelete={() => {
                    setshowAlert(true);
                    setopenCard(item);
                  }}
                  onEdit={() => {
                    setshowModal(true);
                    setopenCard(item);
                  }}
                  item={item}
                />
              );
            })}
        </Table>

        <Spacer height={100} />
      </section>

      {showModal && (
        <Edit
          card={openCard}
          onClose={() => {
            setshowModal(false);
            setopenCard(null);
            getListCards.refetch();
          }}
        />
      )}

      {showAlert && (
        <Alert
          text="Are you sure you want to inactive this question"
          onClose={() => setshowAlert(false)}
          onPress={() => {
            makeInactive({
              variables: {
                adminDeactivateCardId: openCard?._id,
              },
            });
          }}
        />
      )}
    </div>
  );
}

const CardItem = ({ item, onEdit, onDelete }) => {
  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titles[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.caption_text} type="h3" />
      </div>
      <div
        style={{
          width: titles[1].size,
        }}
        className={tabel.three}
      >
        {item?.similar_questions?.map((item, index) => {
          return <Typography text={item} type="h3" />;
        })}
      </div>
      <div
        style={{
          width: titles[2].size,
        }}
        className={tabel.three}
      >
        <Typography
          text={item?.creator?.name ? item?.creator?.name : "Admin"}
          type="h3"
        />
      </div>
      <div
        style={{
          width: titles[3].size,
        }}
        className={tabel.three}
      >
        <Button type={item?.status} text={item?.status} />
        {/* <Typography text={item?.status} type="h3" /> */}
      </div>
      <div
        style={{
          width: titles[4].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.is_premium ? "Pro" : "Normal"} type="h3" />
      </div>
      <div
        style={{
          width: titles[5].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.total_messages_count} type="h3" />
      </div>

      <div
        style={{
          width: "9%",
        }}
        className={tabel.four}
      >
        <Alignment direction="row">
          <Button
            onPress={() => {
              onEdit(item);
            }}
            text={"Edit"}
          />

          <div
            onClick={() => {
              onDelete(item);
            }}
            className={styles.imageBtn}
          >
            <img className={styles.image} src="/close.svg" />
          </div>
        </Alignment>
      </div>
    </div>
  );
};
