import Head from "next/head";
import styles from "../styles/Feed.module.scss";
import Header from "../components/Header";

import { FEEDBACK } from "../graphQL/queries";
import { useQuery } from "@apollo/client";
import { useEffect, useState } from "react";

import getDate from "../functions/getDate";

export default function FeedBack() {
  const [feedback, setFeedback] = useState([]);

  const getFeedback = useQuery(FEEDBACK);

  useEffect(() => {
    if (getFeedback.data) {
      setFeedback(getFeedback.data?.AdminListFeedback);
      //console.log(getFeedback.data);
    }
    if (getFeedback.error) {
      //console.log(getFeedback.error);
      // alert(getFeedback.error?.message);
    }
  }, [getFeedback.data, getFeedback.error]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Feedback | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <text className={styles.welcome}></text>
          <text className={styles.name}>Feedback from creators</text>
          <text className={styles.moto}>Endless Entertainment!</text>
        </div>

        <div className={styles.flatlist}>
          <div className={styles.listcon}>
            <div className={styles.listItem}>
              <div className={styles.imgg1}>
                <img className={styles.inimg} src="/feebp.png" />
              </div>
              <div className={styles.litexts}>
                <text className={styles.headtext}>
                  Total number of feedbacks
                </text>
                <text className={styles.maintext}>{feedback.length} </text>
              </div>
            </div>
          </div>
        </div>

        <div className={styles.searchbutton}>
          <text className={styles.text}>All users</text>
          <div className={styles.search}>
            <input placeholder="Search users"></input>
            <img className={styles.searchimg} src="/search.png"></img>
          </div>
        </div>
        <div className={styles.beginings}>
          <div className={styles.ones}>Names</div>
          <div className={styles.twos}>Date</div>
          <div className={styles.threes}>Suggestions</div>
        </div>

        {feedback.map((item, index) => {
          return (
            <div
              style={{ marginBottom: index == feedback.length - 1 ? 50 : 0 }}
              className={styles.begining}
            >
              <div className={styles.one}>
                <img src={item?.user?.avatar} />{" "}
                {item?.user?.name ? item?.user?.name : "Unknown"}
              </div>
              <div className={styles.two}>{getDate(item.date)}</div>
              <div className={styles.three}>
                <img src="/feedblur.png"></img>
                {item.text}
                {/* <span style={{ color: "#764ffe" }}>Read more</span> */}
              </div>
            </div>
          );
        })}
      </section>
    </div>
  );
}
