import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import { GET_STATS, TRENDING_CARD } from "../graphQL/queries";
import { useQuery } from "@apollo/client";
import { useEffect, useState, useContext } from "react";
import Typography from "../components/Typography";
import Card from "../components/Card";
import Alignment from "../components/Alignment";
import Spacer from "../components/Spacer";
import { AnalyticsDashboard } from "react-analytics-charts";
// Over ten different commonly used charts are available
import { SessionsByDateChart, SessionsGeoChart } from "react-analytics-charts";

export default function Home() {
  const [stats, setstats] = useState({});
  const [trending, settrending] = useState([]);

  const getstats = useQuery(GET_STATS, {
    onCompleted(data) {
      setstats(data?.AdminStats?.json);
    },
  });
  const getTrending = useQuery(TRENDING_CARD, {
    onCompleted(data) {
      settrending(data?.AdminListTrendingCards);
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Overview" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <Spacer height={30} />

        <Alignment style={{ width: "100%" }} direction="row">
          <div style={{ width: "60%" }}>
            <Card
              width="flow"
              textType="h0"
              text={`Real time sign ups`}
              number={stats?.total_signups}
            />
          </div>
          <div style={{ width: "40%", display: "flex" }}>
            <Spacer width={23} />
            <Card
              width="short"
              text={`Total number\nof Users`}
              number={stats?.total_signups}
              emoji="🤩"
              textType="h5"
            />
            <Spacer width={23} />
            <Card
              width="short"
              text={`Total number \nof Questions`}
              number={stats?.total_questions}
              emoji="❓"
              textType="h5"
            />
          </div>
        </Alignment>

        <Spacer height={23} />

        <Alignment style={{ width: "100%" }} direction="row">
          <div
            style={{
              width: "60%",
              display: "flex",
              flex: 1,
            }}
          >
            <Card
              width="flow"
              textType="h0"
              text={`Retention (Sign Up Vs time)`}
            >
              <div
                style={{
                  height: "100%",
                }}
              />
            </Card>
          </div>
          <div
            style={{ width: "40%", display: "flex", flexDirection: "column" }}
          >
            <Spacer width={23} />
            <div
              style={{
                display: "flex",
                flexDirection: "column",
              }}
            >
              <div style={{ width: "100%", display: "flex" }}>
                <Spacer width={23} />
                <Card
                  width="short"
                  text={`Total number\nof Polls`}
                  number={stats?.total_polls}
                  emoji="📝"
                  textType="h5"
                />
                <Spacer width={23} />
                <Card
                  width="short"
                  text={`Total number \nby Upvotes`}
                  number={stats?.total_poll_upovtes}
                  emoji="👍"
                  textType="h5"
                />
              </div>
              <Spacer height={23} />
              <div style={{ width: "100%", display: "flex" }}>
                <Spacer width={23} />
                <Card
                  width="short"
                  text={`Total Earning`}
                  number={
                    "$" +
                    Intl.NumberFormat("en", {
                      notation: "compact",
                    }).format(Number(stats?.total_earning))
                  }
                  emoji="💸"
                  textType="h5"
                />
                <Spacer width={23} />
                <Card
                  width="short"
                  text={`Trending Card`}
                  emoji="🃏"
                  children={
                    <Alignment justify="space-between" direction="row">
                      <Typography
                        text={`${String(trending[0]?.caption_text).substring(
                          0,
                          30
                        )}`}
                        type={"h2"}
                        color="black"
                        style={{
                          width: "50%",
                        }}
                      />
                      <Alignment align="flex-start" direction="column">
                        <Typography text="Messages" type={"h7"} color="black" />
                        <Typography
                          text={trending[0]?.total_messages_count}
                          type={"h2"}
                          color="black"
                        />
                      </Alignment>
                    </Alignment>
                  }
                />
              </div>
            </div>
          </div>
        </Alignment>

        <Spacer height={23} />

        <Card
          style={{
            display: "none",
          }}
          width="flow"
          textType="h0"
          text={`Total number of user( Number of user VS Day / 
Month)`}
        >
          <div
            style={{
              height: 460,
              width: "100%",
            }}
          >
            <AnalyticsDashboard
              authOptions={{
                clientId:
                  "123456789012-abc123def456ghi789jkl012mno345p.apps.googleusercontent.com",
              }}
              renderCharts={(gapi, viewId) => {
                console.log(gapi);
                return (
                  <div
                    style={{
                      height: 460,
                      width: 300,
                      backgroundColor: "green",
                    }}
                  >
                    <SessionsByDateChart
                      gapi={gapi}
                      viewId={viewId}
                      showPageViews
                      showUsers
                    />
                    <SessionsGeoChart
                      gapi={gapi}
                      viewId={viewId}
                      showPageViews
                    />
                  </div>
                );
              }}
            />
          </div>
        </Card>
        <Spacer height={100} />
      </section>
    </div>
  );
}
