import Head from "next/head";
import styles from "../styles/Notification.module.scss";
import Header from "../components/Header";
import { NotiData } from "../context";
import { useContext } from "react";
import Typography from "../components/Typography";

export default function Notification() {
  const { noti, setnoti } = useContext(NotiData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Notification | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Notification" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <div className={styles.flatlist}>
          <div
            onClick={() => {
              setnoti({
                open: true,
                page: 1,
              });
            }}
            className={styles.listcon}
          >
            <div className={styles.listItem}>
              <div className={styles.imgg1x}>
                <img className={styles.imgg1} src="/user.png" />
              </div>

              <div className={styles.maintext}>
                Create <br />
                A General <br /> Notification
              </div>
            </div>
          </div>

          <div
            onClick={() => {
              setnoti({
                open: true,
                page: 2,
              });
            }}
            className={styles.listcon}
          >
            <div className={styles.listItem}>
              <div className={styles.imgg1x}>
                <img className={styles.imgg1} src="/user.png" />
              </div>

              <div className={styles.maintext}>
                Create <br />
                A Recurring <br />
                Notification
              </div>
            </div>
          </div>

          <div
            onClick={() => {
              setnoti({
                open: true,
                page: 3,
              });
            }}
            className={styles.listcon}
          >
            <div className={styles.listItem}>
              <div className={styles.imgg1x}>
                <img className={styles.imgg1} src="/user.png" />
              </div>

              <div className={styles.maintext}>
                Create <br />
                A Specific <br />
                Notification
              </div>
            </div>
          </div>
        </div>

        <div className={styles.spacer} />
        <text className={styles.sometitle}>Some Default Notification</text>

        {/* <div className={styles.flatlist}>
          <div className={styles.listconx}>
            <div className={styles.topconer}>
              <text>Recurring</text>
              <div>
                <img src="/pencil.png" />
              </div>
            </div>
            <div className={styles.listItemx}>
              <text className={styles.l2title}>Subject</text>
              <text className={styles.l2name}>
                Happy Sunday👋, <br />
                Bsocial Buzzing, com..
              </text>
              <text className={styles.l2title}>Body</text>
              <text className={styles.l2body}>
                Happy day, B.Social buzzing, <br />
                come join in the fun!! <br />
                🎉👋🤩😎🤩
              </text>
            </div>
          </div>

          <div className={styles.listconx}>
            <div className={styles.topconer}>
              <text>Send again</text>
              <div>
                <img src="/pencil.png" />
              </div>
            </div>
            <div className={styles.listItemx}>
              <text className={styles.l2title}>Subject</text>
              <text className={styles.l2name}>
                Happy Sunday👋, <br />
                Bsocial Buzzing, com..
              </text>
              <text className={styles.l2title}>Body</text>
              <text className={styles.l2body}>
                Happy day, B.Social buzzing, <br />
                come join in the fun!! <br />
                🎉👋🤩😎🤩
              </text>
            </div>
          </div>
        </div>
      */}
      </section>
    </div>
  );
}
