import Head from "next/head";
import styles from "../styles/Phonebook.module.scss";
import Header from "../components/Header";
import Link from "next/link";
import { useContext } from "react";

import { COUNT_PHONE, GET_PHONEBOOK } from "../graphQL/queries";
import { useQuery, useMutation } from "@apollo/client";
import { useEffect, useState } from "react";
import { PhoneData } from "../context";
import { toaster } from "evergreen-ui";

import getDate from "../functions/getDate";
import Typography from "../components/Typography";
import Table from "../components/Tabel";
import Button from "../components/Button";
import Spacer from "../components/Spacer";

const titles = [
  {
    name: "Name",
    size: "25%",
  },
  {
    name: "Email",
    size: "25%",
  },
  {
    name: "Phone Number",
    size: "20%",
  },
  {
    name: "User ID",
    size: "20%",
  },
];

export default function Phonebook() {
  const { phone, setphone } = useContext(PhoneData);
  const [gh, setgh] = useState(0);
  const [us, setus] = useState(0);
  const [ind, setind] = useState(0);

  const [dropdown, setdropdown] = useState({
    page: -1,
    index: -1,
  });
  const [query, setquery] = useState("");
  const [filter, setfilter] = useState("all");
  const [page, setpage] = useState(0);
  const [phonebook, setphonebook] = useState([]);

  const getstats = useQuery(GET_PHONEBOOK, {
    variables: {
      limit: 10,
      page: page,
    },
    onCompleted(data) {
      setphonebook(data?.PhoneContactList);
    },
  });

  const getGhana = useQuery(COUNT_PHONE, {
    variables: {
      countryCode: "GH",
    },
  });

  const getindia = useQuery(COUNT_PHONE, {
    variables: {
      countryCode: "IN",
    },
  });

  const getUSA = useQuery(COUNT_PHONE, {
    variables: {
      countryCode: "US",
    },
  });

  useEffect(() => {
    if (getGhana.data) {
      setgh(getGhana.data?.AdminCountPhoneContact?.count);
    }
    if (getGhana.error) {
      // //console.log(getGhana.error);
    }

    if (getindia.data) {
      setind(getindia.data?.AdminCountPhoneContact?.count);
    }
    if (getindia.error) {
      // //console.log(getindia.error);
    }

    if (getUSA.data) {
      setus(getUSA.data?.AdminCountPhoneContact?.count);
    }
    if (getUSA.error) {
      // //console.log(getUSA.error);
    }
  }, [
    getGhana.data,
    getGhana.error,

    getindia.data,
    getindia.error,

    getUSA.data,
    getUSA.error,
  ]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Phonebook" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <div className={styles.frow}>
          <div className={styles.listcon}>
            <div className={styles.listItem}>
              <div className={styles.imgg3x}>
                <img className={styles.imgg3} src="/user.png" />
              </div>
              <div className={styles.litexts}>
                <text className={styles.headtext}>
                  Total number in directories
                </text>
                <text className={styles.maintext}>{gh + us + ind} </text>
              </div>

              <div
                onClick={() => {
                  setphone({
                    open: true,
                    page: 1,
                  });
                }}
                className={styles.sendcon}
              >
                <img className={styles.send} src="/send.png" />
              </div>
            </div>
          </div>
          <div className={styles.listcon}>
            <div className={styles.listItem}>
              <div className={styles.imgg3}>
                <img className={styles.inimg} src="/us.png" />
              </div>
              <div className={styles.litexts}>
                <text className={styles.headtext}>USA total directories</text>
                <text className={styles.maintext}>{us} </text>
              </div>

              <div
                onClick={() => {
                  setphone({
                    open: true,
                    page: 2,
                  });
                }}
                className={styles.sendcon}
              >
                <img className={styles.send} src="/send.png" />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.frow}>
          <div className={styles.listcon}>
            <div className={styles.listItem}>
              <div className={styles.imgg3}>
                <img className={styles.inimg} src="/gh.png" />
              </div>
              <div className={styles.litexts}>
                <text className={styles.headtext}>Ghana total directories</text>
                <text className={styles.maintext}>{gh} </text>
              </div>

              <div
                onClick={() => {
                  setphone({
                    open: true,
                    page: 3,
                  });
                }}
                className={styles.sendcon}
              >
                <img className={styles.send} src="/send.png" />
              </div>
            </div>
          </div>
          <div className={styles.listcon}>
            <div className={styles.listItem}>
              <div className={styles.imgg3}>
                <img className={styles.inimg} src="/in.png" />
              </div>
              <div className={styles.litexts}>
                <text className={styles.headtext}>India total directories</text>
                <text className={styles.maintext}>{ind} </text>
              </div>

              <div
                onClick={() => {
                  setphone({
                    open: true,
                    page: 4,
                  });
                }}
                className={styles.sendcon}
              >
                <img className={styles.send} src="/send.png" />
              </div>
            </div>
          </div>
        </div>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="Contacts" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />

        <Table
          columns={5}
          titles={titles}
          onNext={() => {
            // if (Math.ceil(stats?.total_signups / 10) !== page + 1) {
            //   setpage(page + 1);
            // }
          }}
          onPrev={() => {
            // if (page >= 1) {
            //   setpage(page - 1);
            // }
          }}
          totalNumber={"Many"}
          currentNumber={page + 1}
          showFilter={false}
          onSearch={(val) => {
            setquery(val);
          }}
        >
          {phonebook
            .filter((item) => {
              return (
                item?.name?.toLowerCase()?.indexOf(query.toLowerCase()) !== -1
              );
            })
            .map((item, index) => {
              return (
                <UserItem
                  res={alertRes}
                  item={item}
                  onPress={() => {
                    if (item?.status == "inactive") {
                      daUser({
                        variables: {
                          adminActivateDeactivateUserId: item?._id,
                          status: "active",
                        },
                      });
                    } else {
                      setshowAlert(true);
                      setopenUser(item);
                    }
                  }}
                />
              );
            })}
        </Table>
      </section>
    </div>
  );
}

const UserItem = ({ item, onPress, res }) => {
  const [alertRes, setalertRes] = useState(true);

  useEffect(() => {
    if (res && alertRes) {
      setalertRes(false);
      console.log(Math.random());
    }
  }, [res]);

  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titles[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.name} type="h3" />
      </div>
      <div
        style={{
          width: titles[1].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.email} type="h3" />
      </div>
      <div
        style={{
          width: titles[2].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.phone} type="h3" />
      </div>
      <div
        style={{
          width: titles[3].size,
        }}
        className={tabel.three}
      >
        <Typography text={String(item?._id).substring(0, 20)} type="h3" />
      </div>

      <div
        style={{
          width: "9%",
        }}
        className={tabel.four}
      >
        <Button
          onPress={() => {
            onPress();
          }}
          text={item?.status == "active" ? "Deactivate" : "Activate"}
        />
      </div>

      {/* <Alert onClose={() => setshowAlert(false)} onPress={() => {}} /> */}
    </div>
  );
};
