import Head from "next/head";
import styles from "../styles/Home.module.scss";
import tabel from "../styles/Tabel.module.scss";
import Header from "../components/Header";
import { LIST_USER, GET_STATS } from "../graphQL/queries";
import { useQuery, useMutation } from "@apollo/client";
import { A_D_USER } from "../graphQL/mutations";
import { useEffect, useState, useContext } from "react";
import Typography from "../components/Typography";
import Card from "../components/Card";
import Alignment from "../components/Alignment";
import Spacer from "../components/Spacer";
import Table from "../components/Tabel";
import Link from "next/link";
import Button from "../components/Button";
import Alert from "../components/Alert";
import { toaster } from "evergreen-ui";

const titles = [
  {
    name: "Name",
    size: "20%",
  },
  {
    name: "Email",
    size: "20%",
  },
  {
    name: "Phone Number",
    size: "20%",
  },
  {
    name: "User ID",
    size: "20%",
  },
  {
    name: "Referals",
    size: "10%",
  },
];

export default function Profile() {
  const [listUsers, setlistUsers] = useState([]);
  const [showAlert, setshowAlert] = useState(false);
  const [alertRes, setalertRes] = useState(false);
  const [page, setpage] = useState(0);
  const [openUser, setopenUser] = useState(null);

  const [stats, setstats] = useState({});
  const [query, setquery] = useState("");

  const getstats = useQuery(GET_STATS, {
    onCompleted(data) {
      setstats(data?.AdminStats?.json);
    },
  });

  function copyTextToClipboard(text) {
    if (!navigator.clipboard) {
      fallbackCopyTextToClipboard(text);
      return;
    }
    navigator.clipboard.writeText(text).then(
      function () {
        console.log("Async: Copying to clipboard was successful!");
        toaster.success("Copied!");
      },
      function (err) {
        console.error("Async: Could not copy text: ", err);
      }
    );
  }

  // useEffect(() => {
  //   setTimeout(() => {
  //     setalertRes(false);
  //   }, 100);
  // }, [alertRes]);

  const getListUsers = useQuery(LIST_USER, {
    variables: {
      limit: 10,
      page: page,
    },
  });

  useEffect(() => {
    if (getListUsers.data) {
      setlistUsers(getListUsers.data?.AdminListUsers);
      console.log(getListUsers.data);
    }
    if (getListUsers.error) {
      console.log(getListUsers.error);
      // alert(getListUsers.error?.message);
    }
  }, [getListUsers.data, getListUsers.error]);

  const [daUser, daUserQuery] = useMutation(A_D_USER, {
    onCompleted(data) {
      console.log(data);
      toaster.success("Done");
      getListUsers.refetch();
    },
    onError(error) {
      console.log(error);
      toaster.danger("Something happened, Try again");
      alert(error.message);
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Users" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <Spacer height={30} />

        <Alignment direction="row">
          <Card
            text={`Total number \nof Users`}
            number={stats?.total_signups}
            emoji="🤩"
          />
          <Spacer width={27} />
          <Card
            text={`Deactivated \nUser`}
            number={stats?.total_deactivated_users}
            emoji="🫠"
          />
        </Alignment>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="All Users" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          columns={5}
          titles={titles}
          onNext={() => {
            if (Math.ceil(stats?.total_signups / 10) !== page + 1) {
              setpage(page + 1);
            }
          }}
          onPrev={() => {
            if (page >= 1) {
              setpage(page - 1);
            }
          }}
          totalNumber={Math.ceil(stats?.total_signups / 10)}
          currentNumber={page + 1}
          showFilter={false}
          onSearch={(val) => {
            setquery(val);
          }}
        >
          {listUsers
            .filter((item) => {
              return (
                item?.name?.toLowerCase()?.indexOf(query.toLowerCase()) !== -1
              );
            })
            .map((item, index) => {
              return (
                <UserItem
                  res={alertRes}
                  item={item}
                  setshowAlert={setshowAlert}
                  setopenUser={setopenUser}
                  // onPress={() => {
                  //   if (item?.status == "inactive") {
                  //     daUser({
                  //       variables: {
                  //         adminActivateDeactivateUserId: item?._id,
                  //         status: "active",
                  //       },
                  //     });
                  //   } else {
                  //     setshowAlert(true);
                  //     setopenUser(item);
                  //   }
                  // }}
                />
              );
            })}
        </Table>

        <Spacer height={100} />
      </section>

      {showAlert && (
        <Alert
          // showBtn={false}
          showDialog={false}
          text={"https/playcandor.com/app/signup/" + openUser?.username}
          onClose={() => setshowAlert(false)}
          onPress={() => {
            //copy
            copyTextToClipboard(
              "https/playcandor.com/app/signup/" + openUser?.username
            );
          }}
          btnText="Copy"
        />
      )}
    </div>
  );
}

const UserItem = ({ item, onPress, res, setshowAlert, setopenUser }) => {
  const [alertRes, setalertRes] = useState(true);

  useEffect(() => {
    if (res && alertRes) {
      setalertRes(false);
      console.log(Math.random());
    }
  }, [res]);

  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titles[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.name} type="h3" />
        <span
          style={{
            color: "gray",
            transform: "scale(0.8)",
            marginLeft: -6,
          }}
        >{`(${item?.username})`}</span>
      </div>
      <div
        style={{
          width: titles[1].size,
        }}
        className={tabel.three}
      >
        <Typography
          text={String(item?.email).substring(0, 23) + "..."}
          type="h3"
        />
      </div>
      <div
        style={{
          width: titles[2].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.phone} type="h3" />
      </div>
      <div
        style={{
          width: titles[3].size,
        }}
        className={tabel.three}
      >
        <Typography
          text={String(item?._id).substring(0, 20) + "..."}
          type="h3"
        />
      </div>
      <div
        style={{
          width: titles[4].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.referralCount} type="h3" />
      </div>

      <div
        style={{
          width: "9%",
        }}
        className={tabel.four}
      >
        <Button
          onPress={() => {
            // alert("https/playcandor.com/app/signup/" + item?.username);
            setopenUser(item);
            setshowAlert(true);
          }}
          text={"View Link"}
        />
      </div>

      {/* <Alert onClose={() => setshowAlert(false)} onPress={() => {}} /> */}
    </div>
  );
};
