import Head from "next/head";
import styles from "../styles/Home.module.scss";
import tabel from "../styles/Tabel.module.scss";
import Header from "../components/Header";
import { GET_REV_SHARE, LIST_REV, LIST_REV_USERS } from "../graphQL/queries";
import { ADMIN_CLEAR_PAYOUT, ADMIN_MARK_REV_SHARE_AS_PAID, INACTIVATE_CARD } from "../graphQL/mutations";
import { useMutation, useQuery } from "@apollo/client";
import {formatDate} from "date-fns"

import { useEffect, useState, useContext } from "react";
import Typography from "../components/Typography";
import Card from "../components/Card";
import Alignment from "../components/Alignment";
import Spacer from "../components/Spacer";
import Table from "../components/Tabel";
import Edit from "../components/Edit";
import EditPayment from "../components/EditPayment";
import { toaster } from "evergreen-ui";
import Button from "../components/Button";

const titles = [
  {
    name: "Name",
    size: "20%",
  },
  {
    name: "Amount",
    size: "20%",
  },
  {
    name: "Type",
    size: "20%",
  },
  {
    name: "User ID",
    size: "20%",
  },
  {
    name: "Date",
    size: "20%",
  },
];

const titlesRevUsers = [
  {
    name: "Name",
    size: "50%",
  },

  {
    name: "Amount",
    size: "20%",
  },
  {
    name: "User ID",
    size: "30%",
  },
];

const titlesRev = [
  {
    name: "User ID",
    size: "25%",
  },

  {
    name: "Amount",
    size: "25%",
  },
  {
    name: "Date",
    size: "20%",
  },
  {
    name: "Status",
    size: "20%",
  },
  {
    name: "Actions",
    size: "10%",
  },
];

export default function Revenue() {
  const [listRevShare, setlistRevShare] = useState([]);
  const [listRev, setlistRev] = useState([]);
  const [showModal, setshowModal] = useState(false);
  const [openCard, setopenCard] = useState(null);
  const [showEditPayment, setshowEditPayment] = useState(false);
  const [page, setpage] = useState(0);
  const [page2, setpage2] = useState(0);

  const [filter, setfilter] = useState(null);

  const [filterSelected, setfilterSelected] = useState("All");
  const [query, setquery] = useState("");

  const getRev = useQuery(LIST_REV, {
    variables: {
      limit: 10,
      page: page2,
    },
    onCompleted(data) {
      setlistRev(data?.AdmminListPaymentTransactions);
      console.log(data);
    },
    onError(error) {
      console.log(error);
    },
  });
  /* const getRevUsers = useQuery(LIST_REV_USERS, {
    variables: {
      limit: 10,
      page: page2,
    },
    onCompleted(data) {
      setlistRevusers(data?.AdminListRevShareUsers);
      console.log(data);
    },
    onError(error) {
      console.log(error);
    },
  }); */

  const getRevShare = useQuery(GET_REV_SHARE, {
    variables: {
      limit: 10,
      page: page,
    },
    onCompleted(data) {
      setlistRevShare(data?.AdminListRevSharePaymentRequests);
      console.log(data);
    },
    onError(error) {
      console.log(error);
    },
  });

  const [adminClearPayout, adminClearPayoutQuery] = useMutation(
    ADMIN_CLEAR_PAYOUT,
    {
      onCompleted(data) {
        console.log(data);
        toaster.success("Payment Cleared.");
        setshowEditPayment(false);
        getRevShare.refetch();
      },

      onError(error) {
        console.log(error);
        toaster.danger(error.message);
      },
    }
  );

  const totalRevShare = listRevShare?.reduce((acc, item) => acc + item?.amount, 0);
  const totalPayments = listRev?.reduce((acc, item) => (cardTypeAmountMap?.[item?.productId] || 0) + acc, 0);

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Revenue" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <Spacer height={30} />

        <Alignment direction="row">
          <Card text={`Total\nPayments`} number={`$${totalPayments?.toFixed(2)}`} emoji="💸" />
          <Spacer width={27} />
          <Card text={`Revenue\n Share`} number={`$${totalRevShare?.toFixed(2)}`} emoji="💸" />
        </Alignment>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="All Trasactions" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          columns={5}
          titles={titles}
          btnText="Edit"
          onPress={() => {}}
          onNext={() => {
            // if (Math.ceil(stats?.total_questions / 10) !== page + 1) {
            setpage(page2 + 1);
            // }
          }}
          onPrev={() => {
            if (page2 >= 1) {
              setpage2(2 - 1);
            }
          }}
          totalNumber={"any"}
          currentNumber={page2 + 1}
          showFilter={false}
          showSearch={false}
        >
          {listRev
            .filter((item) => {
              if (filterSelected == "All" && query == "") {
                return true;
              } else {
                return (
                  item.status
                    .toLowerCase()
                    .indexOf(filterSelected.toLowerCase()) !== -1 ||
                  (item.is_premium && filterSelected.toLowerCase() == "pro") ||
                  (!item.is_premium &&
                    filterSelected.toLowerCase() == "normal") ||
                  filterSelected.toLowerCase() == "admin" ||
                  filterSelected.toLowerCase() == "user" ||
                  item?.caption_text
                    ?.toLowerCase()
                    ?.includes(query.toLowerCase())
                );
              }
            })
            .map((item, index) => {
              return (
                <CardItem
                  onDelete={() => {
                    setshowEditPayment(true);
                    setopenCard(item);
                  }}
                  onEdit={() => {
                    setshowModal(true);
                    setopenCard(item);
                  }}
                  item={item}
                  refetch={()=>getRevShare.refetch()}
                />
              );
            })}
        </Table>

        <Spacer height={100} />
        <div className={styles.toptwo}>
          <Typography text="Rev-Share Withdrawal Requests" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          columns={5}
          titles={titlesRev}
          btnText="Edit"
          onPress={() => {}}
          onNext={() => {
            // if (Math.ceil(stats?.total_questions / 10) !== page + 1) {
            setpage(page + 1);
            // }
          }}
          onPrev={() => {
            if (page >= 1) {
              setpage(page - 1);
            }
          }}
          totalNumber={"any"}
          currentNumber={page + 1}
          showFilter={false}
          showSearch={false}
        >
          {listRevShare
            .filter((item) => {
              if (filterSelected == "All" && query == "") {
                return true;
              } else {
                return (
                  item.status
                    .toLowerCase()
                    .indexOf(filterSelected.toLowerCase()) !== -1 ||
                  (item.is_premium && filterSelected.toLowerCase() == "pro") ||
                  (!item.is_premium &&
                    filterSelected.toLowerCase() == "normal") ||
                  filterSelected.toLowerCase() == "admin" ||
                  filterSelected.toLowerCase() == "user" ||
                  item?.caption_text
                    ?.toLowerCase()
                    ?.includes(query.toLowerCase())
                );
              }
            })
            .map((item, index) => {
              return (
                <CardItemRev
                  onMore={() => {
                    setshowEditPayment(true);
                    setopenCard(item);
                  }}
                  onEdit={() => {
                    setshowEditPayment(true);
                    setopenCard(item);
                  }}
                  item={item}
                  refetch={()=>getRevShare.refetch()}
                />
              );
            })}
        </Table>
        <Spacer height={100} />
      </section>

      {showModal && (
        <Edit
          card={openCard}
          onClose={() => {
            setshowModal(false);
            setopenCard(null);
            getRevShare.refetch();
          }}
        />
      )}

      {showEditPayment && (
        <EditPayment
          titles={titlesRev}
          text="Are you sure you want to inactive this question"
          onClose={() => setshowEditPayment(false)}
          onPress={() => {
            adminClearPayout({
              variables: {
                withrawlRequestId: openCard?._id,
                paidAmount: openCard?.amount,
                paymentMethod: "none",
              },
            });
          }}
        />
      )}
    </div>
  );
}

const cardTypeAmountMap = {
  "cdrh_199": 1.99,
  "cd_399_1w": 3.99
}

const CardItem = ({ item, onEdit, onDelete }) => {
  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titles[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.user?.name} type="h3" />
      </div>
      <div
        style={{
          width: titles[1].size,
        }}
        className={tabel.three}
      >
        <Typography text={`$${cardTypeAmountMap?.[item?.productId]||0}`} type="h3" />
      </div>
      <div
        style={{
          width: titles[2].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.productId} type="h3" />
      </div>
      <div
        style={{
          width: titles[3].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.user?._id} type="h3" />
      </div>
      <div
        style={{
          width: titles[4].size,
        }}
        className={tabel.three}
      >
        <Typography text={Date(item?.created_at).substring(0, 16)} type="h3" />
      </div>
      <div
        style={{
          width: "9%",
        }}
        className={tabel.four}
      >
        {/* <Alignment direction="row">
          <Button
            onPress={() => {
              onMore(item);
            }}
            text={"More"}
          />
          <Button
            onPress={() => {
              onEdit(item);
            }}
            text={"Edit"}
          />
        </Alignment> */}
      </div>
    </div>
  );
};

const CardItemRev = ({ item, onEdit, onMore, refetch }) => {
  const [loading, setLoading] = useState(false);
  const [adminMarkRevShareAsPaid, adminMarkRevShareAsPaidData] = useMutation(
    ADMIN_MARK_REV_SHARE_AS_PAID,
    {
      onCompleted(data) {
        console.log(data);
        toaster.success("Marked as paid.");
        refetch()
        setLoading(false)
      },
      onError(error) {
        console.log(error);
        toaster.danger(error.message);
        setLoading(false)
      },
    }
  );
  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titlesRev[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.user_id} type="h3" />
      </div>
      <div
        style={{
          width: titlesRev[1].size,
        }}
        className={tabel.three}
      >
        <Typography text={`$${(item?.amount||0)?.toFixed(2)}`} type="h3" />
      </div>
      <div
        style={{
          width: titlesRev[2].size,
        }}
        className={tabel.three}
      >
        <Typography text={formatDate(new Date(Number(item?.created_at)), "MMM dd, yyyy")} type="h3" />
      </div>
      <div
        style={{
          width: titlesRev[3].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.status} type="h3" />
      </div>
      <div
        style={{
          width: titlesRev[4].size,
        }}
        className={tabel.three}
      >
        <Button onPress={()=>{
          let conf = window.confirm("Do you want to proceed with marking this as paid ?")
          if(conf){
            setLoading(true)
            adminMarkRevShareAsPaid({
              variables: {
                id: item?._id
              }
            })
          }
        }} inactive={item?.status !== "pending"} type={"live"} text={loading ? "Wait..." : item?.status == "paid" ? "Paid" : "Pay"} />
      </div>
      <div
        style={{
          width: "9%",
        }}
        className={tabel.three}
      >
      </div>
    </div>
  );
};
const CardItemRevUser = ({ item, onEdit, onMore }) => {
  return (
    <div className={tabel.tabelRow}>
      <div
        style={{
          width: titlesRevUsers[0].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.name} type="h3" />
      </div>
      <div
        style={{
          width: titlesRevUsers[1].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?.rev_share} type="h3" />
      </div>
      <div
        style={{
          width: titlesRevUsers[2].size,
        }}
        className={tabel.three}
      >
        <Typography text={item?._id} type="h3" />
      </div>

      <div
        style={{
          width: "9%",
        }}
        className={tabel.four}
      >
        <Alignment direction="row">
          <Button
            onPress={() => {
              onMore(item);
            }}
            text={"More"}
          />
          <Button
            onPress={() => {
              onEdit(item);
            }}
            text={"Edit"}
          />
        </Alignment>
      </div>
    </div>
  );
};
