import Head from "next/head";
import styles from "../styles/Home.module.scss";
import tabel from "../styles/Tabel.module.scss";
import Header from "../components/Header";
import { LIST_POLL, GET_STATS, POLL_RESULT } from "../graphQL/queries";
import { useQuery, useMutation } from "@apollo/client";
import { INACTIVATE_POLL } from "../graphQL/mutations";
import { useEffect, useState, useContext } from "react";
import Typography from "../components/Typography";
import Card from "../components/Card";
import Alignment from "../components/Alignment";
import Spacer from "../components/Spacer";
import Table from "../components/Tabel";
import Link from "next/link";
import Button from "../components/Button";
import Create from "../components/Create";
import Alert from "../components/Alert";
import { EditIcon, toaster } from "evergreen-ui";
import EditPoll from "../components/EditPoll";

var sortOrder = ["live", "priotized", "private", "inactive"];

const titles = [
  {
    name: "Name",
    size: "20%",
  },
  {
    name: "Poll Submitted",
    size: "25%",
  },
  {
    name: "Bragging name",
    size: "15%",
  },
  {
    name: "Poll Type",
    size: "15%",
  },
  {
    name: "Week",
    size: "12%",
  },
  {
    name: "Status",
    size: "10%",
  },
  {
    name: "Upvotes",
    size: "7%",
  },
];

const titles2 = [
  {
    name: "Name",
    size: "25%",
  },
  {
    name: "Poll Submitted",
    size: "35%",
  },
  {
    name: "Bragging name",
    size: "20%",
  },

  {
    name: "Week",
    size: "20%",
  },
  {
    name: "Positions",
    size: "10%",
  },
];
export default function Submit() {
  const [listPolls, setlistPolls] = useState([]);
  const [listPolls2, setlistPolls2] = useState([]);
  const [showModal, setshowModal] = useState(false);
  const [showModal2, setshowModal2] = useState(false);
  const [openPoll, setopenPoll] = useState(null);
  const [page, setpage] = useState(0);
  const [page2, setpage2] = useState(0);

  const [filter, setfilter] = useState(null);

  const [showAlert, setshowAlert] = useState(false);
  const [openCard, setopenCard] = useState(null);
  // const [openCard, setopenCard] = useState(null);

  const [stats, setstats] = useState({});
  const [filterSelected, setfilterSelected] = useState("All");
  const [query, setquery] = useState("");
  const [filterSelected2, setfilterSelected2] = useState("All");
  const [query2, setquery2] = useState("");

  const getstats = useQuery(GET_STATS, {
    onCompleted(data) {
      setstats(data?.AdminStats?.json);
    },
  });

  const getlistPolls = useQuery(LIST_POLL, {
    variables: {
      limit: 10,
      page: page,
      status: filter,
    },
    onCompleted(data) {
      let arr = [...data?.AdminListPollCards].sort((a, b) => {
        if (a.status < b.status) {
          return -1;
        }
        if (a.status > b.status) {
          return 1;
        }
        return 0;
        // a.week_title <= b.week_title ? 1 : -1;
      });

      setlistPolls(arr);

      console.log(data?.AdminListPollCards);
    },
  });

  const getlistPolls2 = useQuery(POLL_RESULT, {
    variables: {
      limit: 1,
      page: page2,
    },
    onCompleted(data) {
      setlistPolls2(data?.AdminWeeklyStats);
    },
  });

  const [makeInactive, makeInactiveQuery] = useMutation(INACTIVATE_POLL, {
    onCompleted(data) {
      console.log(data);
      toaster.warning("Poll inactivated");
      getlistPolls.refetch();
    },

    onError(error) {
      console.log(error);
      toaster.danger(error.message);
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Candor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <section className={styles.main}>
        <Header />

        <div className={styles.toptwo}>
          <Typography text="Submit Poll" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>

        <Spacer height={30} />

        <Alignment direction="row">
          <Card
            text={`Total number\nof Polls`}
            number={stats?.total_polls}
            emoji="📝"
          />
          <Spacer width={27} />
          <Card
            text={`Total number\nof upvotes`}
            number={stats?.total_poll_upovtes}
            emoji="👍"
          />
        </Alignment>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="All Submits Polls" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          titles={titles}
          onNext={() => {
            if (Math.ceil(stats?.total_polls / 10) !== page + 1) {
              setpage(page + 1);
            }
          }}
          onPrev={() => {
            if (page >= 1) {
              setpage(page - 1);
            }
          }}
          totalNumber={Math.ceil(stats?.total_polls / 10)}
          currentNumber={page + 1}
          filterSelected={filterSelected}
          filterList={[
            "All",
            "Normal",
            "Pro",
            "Live",
            "Priotized",
            "Private",
            "Inactive",
            "Live_awaiting",
          ]}
          onSelectFilter={(item) => {
            setfilterSelected(item);
            if (
              [
                "live",
                "inactive",
                "private",
                "priotized",
                "live_awaiting",
              ].includes(item?.toLowerCase())
            ) {
              setfilter(item?.toLowerCase());
            } else {
              setfilter(null);
            }
          }}
          onSearch={(val) => {
            setquery(val);
          }}
        >
          {listPolls
            .sort((a, b) => {
              if (a?.status == b?.status) {
                // If the elements both have the same `status`,
                return true; // Compare the elements by `name`.
              } else {
                // Otherwise,
                return (
                  sortOrder?.indexOf(a?.status) - sortOrder?.indexOf(b?.status)
                ); // Substract indexes, If element `a` comes first in the array, the returned value will be negative, resulting in it being sorted before `b`, and vice versa.
              }
            })
            .filter((item) => {
              if (filterSelected == "All" && query == "") {
                return true;
              } else {
                return (
                  item.status
                    .toLowerCase()
                    .indexOf(filterSelected.toLowerCase()) !== -1 ||
                  (item.is_paid && filterSelected.toLowerCase() == "pro") ||
                  (!item.is_paid && filterSelected.toLowerCase() == "normal") ||
                  item?.caption_text
                    ?.toLowerCase()
                    ?.includes(query.toLowerCase())
                );
              }
            })
            .map((item, index) => {
              return (
                <div className={tabel.tabelRow}>
                  <div
                    style={{
                      width: titles[0].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.submitted_by?.name} type="h3" />
                  </div>
                  <div
                    style={{
                      width: titles[1].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.text} type="h3" />;
                  </div>
                  <div
                    style={{
                      width: titles[2].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography
                      text={
                        item?.brag_name
                          ? item?.brag_name
                          : item?.submitted_by?.name
                      }
                      type="h3"
                    />
                  </div>
                  <div
                    style={{
                      width: titles[3].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography
                      text={item?.is_paid ? "Pro" : "Normal"}
                      type="h3"
                    />
                  </div>
                  <div
                    style={{
                      width: titles[4].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.week_title} type="h3" />
                  </div>
                  <div
                    style={{
                      width: titles[5].size,
                    }}
                    className={tabel.three}
                  >
                    <Button type={item?.status} text={item?.status} />
                  </div>
                  <div
                    style={{
                      width: titles[6].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.total_votes} type="h3" />
                  </div>
                  <div
                    style={{
                      width: "9%",
                    }}
                    className={tabel.four}
                  >
                    <Alignment direction="row">
                      <Button
                        onPress={() => {
                          setshowModal2(true);
                          setopenCard(item);
                          console.log(item);
                        }}
                        text={"Edit"}
                      />

                      <div
                        onClick={() => {
                          setshowAlert(true);
                          setopenCard(item);
                        }}
                        className={styles.imageBtn}
                      >
                        <img className={styles.image} src="/close.svg" />
                      </div>
                    </Alignment>
                  </div>
                </div>
              );
            })}
        </Table>

        <Spacer height={70} />
        <div className={styles.toptwo}>
          <Typography text="Results of Polls" type={"h1"} />
          <Typography text="Only Truths, No Lies!" type={"h2"} />
        </div>
        <Spacer height={10} />
        <Table
          titles={titles2}
          onNext={() => {
            // if (Math.ceil(stats?.total_polls / 10) !== page2 + 1) {
            setpage2(page2 + 1);
            // }
          }}
          onPrev={() => {
            if (page2 >= 1) {
              setpage2(page2 - 1);
            }
          }}
          totalNumber={"many"}
          currentNumber={page2 + 1}
          filterSelected={filterSelected2}
          filterList={["All", "Normal", "Pro"]}
          onSelectFilter={(item) => {
            setfilterSelected2(item);
          }}
          onSearch={(val) => {
            setquery2(val);
          }}
        >
          {listPolls2[0]?.polls
            .slice(0, 5)
            .filter((item) => {
              if (filterSelected2 == "All" && query2 == "") {
                return true;
              } else {
                return (
                  item.status
                    .toLowerCase()
                    .indexOf(filterSelected2.toLowerCase()) !== -1 ||
                  (item.is_paid && filterSelected2.toLowerCase() == "pro") ||
                  (!item.is_paid &&
                    filterSelected2.toLowerCase() == "normal") ||
                  item?.caption_text
                    ?.toLowerCase()
                    ?.includes(query2.toLowerCase())
                );
              }
            })
            .map((item, index) => {
              return (
                <div className={tabel.tabelRow}>
                  <div
                    style={{
                      width: titles2[0].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.submitted_by?.name} type="h3" />
                  </div>
                  <div
                    style={{
                      width: titles2[1].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.text} type="h3" />;
                  </div>
                  <div
                    style={{
                      width: titles2[2].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography
                      text={
                        item?.brag_name
                          ? item?.brag_name
                          : item?.submitted_by?.name
                      }
                      type="h3"
                    />
                  </div>

                  <div
                    style={{
                      width: titles2[3].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={item?.week_title} type="h3" />
                  </div>
                  <div
                    style={{
                      width: titles2[4].size,
                    }}
                    className={tabel.three}
                  >
                    <Typography text={index + 1} type="h3" />
                  </div>

                  <div
                    style={{
                      width: "9%",
                    }}
                    className={tabel.four}
                  >
                    <Button
                      onPress={() => {
                        setshowModal(true);
                        setopenPoll(item);
                      }}
                      text={"Create"}
                    />
                  </div>
                </div>
              );
            })}
        </Table>
        <Spacer height={100} />
      </section>

      {showModal && (
        <Create
          poll={openPoll}
          onClose={() => {
            setshowModal(false);
            setopenPoll(null);
            getlistPolls.refetch();
          }}
        />
      )}

      {showModal2 && (
        <EditPoll
          poll={openCard}
          onClose={() => {
            setshowModal2(false);
            setopenCard(null);
            getlistPolls.refetch();
          }}
        />
      )}

      {showAlert && (
        <Alert
          text="Are you sure you want to inactive this poll"
          onClose={() => setshowAlert(false)}
          showDialog={true}
          onPress={(text) => {
            makeInactive({
              variables: {
                adminDeactivatePollCardId: openCard?._id,
                inactiveReason: text,
              },
            });
          }}
        />
      )}
    </div>
  );
}
